version: '2'
services:
    dns:
        image: fabriziogaliano/docker-bind-gui
        #build:
        #   context: .

        container_name: bind_dns_gui
        
        environment:
           GUIPWD_WEBMIN: furriuni

#        volumes:
#           - "./data/bind:/data/bind"
#           - "./var/cache:/var/cache/bind"
#           - "./var/dynamic:/var/dynamic"

        ports:
           - "53:53/udp"
           - "53:53"
           - "10000:10000"

        command: bash /scripts/changeWebminPassword.sh



        